version: '3.8'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=base_db

  keycloak:
      image: quay.io/keycloak/keycloak
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_PORT: 5442
        DB_DATABASE: keycloak_db
        DB_USER: keycloak
        DB_PASSWORD: keycloak
      command: start-dev
      ports:
        - "9090:8080"
      depends_on:
        - keycloak_db

  keycloak_db:
        image: postgres
        environment:
          POSTGRES_DB: keycloak
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak
        ports:
          - "5442:5432"
        volumes:
          - pi-pgdata:/var/lib/postgresql/data
  redis:
      image: redis
      ports:
        - "6380:6379"
      volumes:
        - pi-redis-data:/data
volumes:
  pgdata:
  pi-pgdata:
  pi-redis-data:



