name: Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Copy .env.example to .env
        run: cp .env.example .env && echo "NODE_ENV=production" > .env

      - name: Build Nest App
        run: npm run build

      - name: Copy .env.example to dist
        run: cp .env dist

      - name: Deploy to Vultr
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VULTR_SSH_HOST }}
          username: ${{ secrets.VULTR_SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.VULTR_SSH_PORT }}
          source: dist/
          target: ~/nest-app
