name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install, Build, Run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VULTR_SSH_HOST  }}
          username: ${{ secrets.VULTR_SSH_USER }}
          key: ${{ secrets.SSH_KEY  }}
          port: ${{ secrets.VULTR_SSH_PORT  }}
          script: |
            cd ~/nest-pi-logi && git pull && npm install && npm run prepare
            cd ~/nest-pi-logi && npm run start:prod
