# - name: Copy .env.example to .env
# run: cp .env.example .env && sed -i 's/^NODE_ENV=.*$/NODE_ENV=production/' .env

name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SSH to Server, Clone, and Build
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY "$VULTR_SSH_USER@$VULTR_SSH_HOST" 'cd ~/nest-pi-logi && git pull && npm install && npm run build'

      - name: Start the Application
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY "$VULTR_SSH_USER@$VULTR_SSH_HOST" 'cd ~/nest-pi-logi && npm start'
